# Generated by Django 5.1.7 on 2025-03-27 10:26

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_id', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', editable=False, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LegalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_submitted_to_legal', models.CharField(blank=True, choices=[('16/17', '16/17'), ('17/18', '17/18'), ('18/19', '18/19'), ('19/20', '19/20'), ('20/21', '20/21'), ('21/22', '21/22'), ('22/23', '22/23'), ('23/24', '23/24'), ('24/25', '24/25'), ('25/26', '25/26'), ('26/27', '26/27'), ('27/28', '27/28')], max_length=10, null=True)),
                ('fy_deed_signed', models.CharField(blank=True, choices=[('16/17', '16/17'), ('17/18', '17/18'), ('18/19', '18/19'), ('19/20', '19/20'), ('20/21', '20/21'), ('21/22', '21/22'), ('22/23', '22/23'), ('23/24', '23/24'), ('24/25', '24/25'), ('25/26', '25/26'), ('26/27', '26/27'), ('27/28', '27/28')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, choices=[('Legacy', 'Legacy'), ('Current', 'Current')], max_length=10, null=True)),
                ('case_status', django_fsm.FSMField(blank=True, choices=[('initiated', 'initiated'), ('assigned', 'assigned'), ('updated', 'updated')], default='initiated', max_length=50, null=True)),
                ('legal_status', models.CharField(blank=True, choices=[('Compliance engagement', 'Compliance engagement'), ('Consent Judgement', 'Consent Judgement'), ('Deed of settlement', 'Deed of settlement'), ('Deed signed. Pending confirmation of fully paid', 'Deed signed. Pending confirmation of fully paid'), ('Employer Closed', 'Employer Closed'), ('Execution', 'Execution'), ('Fully Paid', 'Fully Paid'), ('Litigation', 'Litigation'), ('Negotiation', 'Negotiation'), ('Notice of Intention to sue', 'Notice of Intention to sue'), ('Notice of Motion', 'Notice of Motion'), ('Orders issued', 'Orders issued'), ('Penalty waiver', 'Penalty waiver'), ('Plea Bargaining Agreement', 'Plea Bargaining Agreement'), ('Prosecution /Warrant', 'Prosecution /Warrant'), ('Prosecution', 'Prosecution'), ('Reconciliation Agreement', 'Reconciliation Agreement'), ('Returned to Compliance', 'Returned to Compliance'), ('Under receivership', 'Under receivership')], max_length=50, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nssf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('audited_period_startdate', models.DateField(blank=True, null=True)),
                ('audited_period_enddate', models.DateField(blank=True, null=True)),
                ('total_arrears', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('special_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('penalties', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ten_percent_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('detailed_status', models.TextField(blank=True, null=True)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('courtfiling_date', models.DateField(blank=True, null=True)),
                ('nexthearing_date', models.DateField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='legalfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HearingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nexthearing_date', models.DateField()),
                ('description', models.TextField()),
                ('legal_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='Legal2025.legalfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('legal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('courtfiling_date', models.DateField(blank=True, null=True)),
                ('nexthearing_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal2025_comments', to=settings.AUTH_USER_MODEL)),
                ('legal_file', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Legal2025.legalfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_attachments', to='Legal2025.comment')),
                ('legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_attachments', to='Legal2025.legalfiles')),
            ],
        ),
        migrations.CreateModel(
            name='LegalFilesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('legalfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legallogs', to='Legal2025.legalfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_arrears', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=20)),
                ('penalty_10percent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='Legal2025.legalfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference_number', models.CharField(max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('payment_date', models.DateField()),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Legal2025.installment')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Legal2025.reconciliationagreement')),
            ],
        ),
        migrations.AddField(
            model_name='installment',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Legal2025.reconciliationagreement'),
        ),
    ]
