# Generated by Django 5.1.7 on 2025-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal2025', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalfiles',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
