# Generated by Django 5.1.7 on 2025-03-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whistleblower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('nssf_number', models.CharField(max_length=900)),
                ('type', models.CharField(max_length=900)),
                ('date_submitted', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('user_id', models.CharField(blank=True, max_length=900, null=True)),
                ('company_number', models.CharField(max_length=9000)),
                ('company_name', models.CharField(max_length=9000)),
                ('number_employees', models.CharField(max_length=900)),
                ('physical_address', models.TextField()),
                ('director', models.CharField(max_length=9000)),
                ('short_title', models.TextField()),
                ('description', models.TextField()),
                ('other_info', models.TextField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField()),
                ('auditor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.CharField(blank=True, choices=[('Statement query', 'Statement query'), ('Non Registered Employer', 'Non Registered Employer'), ('Known member from a registered employer', 'Known member from a registered employer'), ('UnKnown member from a registered employer', 'UnKnown member from a registered employer')], max_length=100, null=True)),
                ('updated_nssf_number', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_type', models.CharField(blank=True, choices=[('Statement issues', 'Statement issues'), ('Non Payment', 'Non Payment')], max_length=50, null=True)),
                ('updated_company_number', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_anonymous', models.BooleanField(default=False, null=True)),
                ('updated_member_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('updated_member_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_work_from_date', models.DateField(blank=True, null=True)),
                ('updated_work_to_date', models.DateField(blank=True, null=True)),
                ('ongoing_audit', models.BooleanField(default=False, null=True)),
                ('ongoing_auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('in_legal', models.BooleanField(default=False, null=True)),
                ('registered_employer', models.BooleanField(default=False, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('audited_recently_or_in_legal', models.BooleanField(default=False, null=True)),
                ('work_scope_known', models.BooleanField(default=False, null=True)),
                ('case_profiling_result', models.CharField(blank=True, max_length=255, null=True)),
                ('CRM_case_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bi_auditor_username', models.CharField(blank=True, max_length=255, null=True)),
                ('bi_auditor_user_id', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('from_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('comment_mode', models.CharField(max_length=50)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhistleblowerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed_status', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('whistleblower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='feedback2024.whistleblower')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('whistleblowerLog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback2024.whistleblowerlog')),
            ],
        ),
    ]
