# Generated by Django 4.0.4 on 2024-08-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whistleblower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('nssf_number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('date_submitted', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_number', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('number_employees', models.IntegerField()),
                ('physical_address', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('short_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('other_info', models.TextField()),
            ],
        ),
    ]
