# Generated by Django 5.1.7 on 2025-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='nssf_number',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
