# Generated by Django 4.0.4 on 2024-08-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0002_alter_whistleblower_number_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='company_name',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='company_number',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='director',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='key',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='nssf_number',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='number_employees',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='short_title',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='type',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='user_id',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
