# Generated by Django 5.1.7 on 2025-03-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0002_alter_whistleblower_nssf_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='company_name',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='company_number',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='director',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='number_employees',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='short_title',
            field=models.TextField(null=True),
        ),
    ]
