# Generated by Django 4.0.4 on 2024-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0003_alter_whistleblower_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='company_name',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='company_number',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='director',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='short_title',
            field=models.TextField(),
        ),
    ]
