# Generated by Django 4.0.4 on 2024-08-31 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0004_alter_whistleblower_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblower',
            name='auditor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='auditor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
