# Generated by Django 4.0.4 on 2024-08-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0005_whistleblower_auditor_id_whistleblower_auditor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
