# Generated by Django 4.0.4 on 2024-08-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0006_alter_whistleblower_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconcilereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssf_number', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Statement issues', 'Statement issues'), ('Non Payment', 'Non Payment')], max_length=50)),
                ('company_number', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('anonymous', models.BooleanField(default=False)),
                ('member_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('member_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_from_date', models.DateField()),
                ('work_to_date', models.DateField(blank=True, null=True)),
                ('ongoing_audit', models.BooleanField(default=False)),
                ('ongoing_auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('in_legal', models.BooleanField(default=False)),
                ('registered_employer', models.BooleanField(default=False)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback2024.whistleblower')),
            ],
        ),
    ]
