# Generated by Django 4.0.4 on 2024-09-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0007_reconcilereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
