# Generated by Django 4.0.4 on 2024-09-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0009_alter_reconcilereport_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblower',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='in_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='ongoing_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='ongoing_auditor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='registered_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_company_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_member_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_member_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_nssf_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_type',
            field=models.CharField(blank=True, choices=[('Statement issues', 'Statement issues'), ('Non Payment', 'Non Payment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_work_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='updated_work_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
