# Generated by Django 4.0.4 on 2024-09-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0010_whistleblower_extra_info_whistleblower_in_legal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reconcilereport',
        ),
    ]
