# Generated by Django 4.0.4 on 2024-09-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0013_whistleblowerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblowerlog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('whistleblowerLog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback2024.whistleblowerlog')),
            ],
        ),
    ]
