# Generated by Django 4.0.4 on 2024-09-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0015_whistleblowerlog_whistleblower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whistleblowerlog',
            name='whistleblower',
        ),
    ]
