# Generated by Django 4.0.4 on 2024-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0017_whistleblowerlog_whistleblower'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblower',
            name='audited_recently_or_in_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='case_profiling_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='work_scope_known',
            field=models.BooleanField(default=False),
        ),
    ]
