# Generated by Django 4.0.4 on 2024-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0018_whistleblower_audited_recently_or_in_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblower',
            name='CRM_case_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
