# Generated by Django 4.0.4 on 2024-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0019_whistleblower_crm_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblower',
            name='profile',
            field=models.CharField(blank=True, choices=[('Statement query', 'Statement query'), ('Employer is not registered', 'Employer is not registered'), ('Employer is registered and member is known', 'Employer is registered and member is known'), ('Employer is registered and member is anonymous', 'Employer is registered and member is anonymous')], max_length=100, null=True),
        ),
    ]
