# Generated by Django 4.0.4 on 2024-09-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0020_whistleblower_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='whistleblowerLog',
            new_name='whistleblowerLog_case',
        ),
    ]
