# Generated by Django 4.0.4 on 2024-10-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0022_rename_whistleblowerlog_case_attachment_whistleblowerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblowerlog',
            name='review_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='profile',
            field=models.CharField(blank=True, choices=[('Statement query', 'Statement query'), ('Non Registered Employer', 'Non Registered Employer'), ('Known member from a registered employer', 'Known member from a registered employer'), ('UnKnown member from a registered employer', 'UnKnown member from a registered employer')], max_length=100, null=True),
        ),
    ]
