# Generated by Django 4.0.4 on 2024-10-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0023_whistleblowerlog_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblowerlog',
            name='confirmed_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
