# Generated by Django 4.0.4 on 2024-10-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0024_whistleblowerlog_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblower',
            name='bi_auditor_user_id',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='whistleblower',
            name='bi_auditor_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
