# Generated by Django 5.1.4 on 2025-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0025_whistleblower_bi_auditor_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
