# Generated by Django 5.1.4 on 2025-01-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback2024', '0026_alter_whistleblower_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistleblower',
            name='audited_recently_or_in_legal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='in_legal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='ongoing_audit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='registered_employer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='updated_anonymous',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblower',
            name='work_scope_known',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
