# Generated by Django 4.0.4 on 2024-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nssfmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nssf_number', models.CharField(max_length=20)),
                ('employer', models.CharField(max_length=100)),
                ('employer_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('mothers_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
            ],
        ),
    ]
