# Generated by Django 4.0.4 on 2024-04-18 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fliteracyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('employer', models.CharField(max_length=100)),
                ('employer_number', models.CharField(max_length=100)),
                ('fl_advisors_involved', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('program', models.CharField(choices=[('Money Talk', 'Money Talk'), ('Townhall', 'Townhall'), ('Webinar', 'Webinar')], max_length=100)),
                ('delivery_mode', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=100)),
                ('on_spot_feedback', models.BooleanField(default=False)),
                ('rms_involved', models.ManyToManyField(limit_choices_to={'groups__name': 'officers'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
