# Generated by Django 4.0.4 on 2024-04-22 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fliteracyapp', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fl_event',
            name='rms_involved',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Officers'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
