# Generated by Django 4.0.4 on 2024-04-22 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fliteracyapp', '0004_alter_fl_event_rms_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fl_event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='employer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='fl_advisors_involved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='program',
            field=models.CharField(blank=True, choices=[('Money Talk', 'Money Talk'), ('Townhall', 'Townhall'), ('Webinar', 'Webinar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fl_event',
            name='rms_involved',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Officers'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
