# Generated by Django 4.0.4 on 2024-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fliteracyapp', '0005_alter_fl_event_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='fliteracyapp/media/attachments/'),
        ),
    ]
