# Generated by Django 4.0.4 on 2024-05-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fliteracyapp', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nssfmember',
            name='employer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nssfmember',
            name='employer_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nssfmember',
            name='fathers_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nssfmember',
            name='mothers_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nssfmember',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nssfmember',
            name='nssf_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nssfmember',
            name='phone',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
