# Generated by Django 4.0.4 on 2024-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fliteracyapp', '0010_alter_nssfmember_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='flattachments/'),
        ),
    ]
