# Generated by Django 4.0.4 on 2024-05-11 07:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fliteracyapp', '0012_alter_attachment_file_alter_fl_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fl_event',
            name='fl_advisors_involved',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Anna Maria Sanyu', 'Anna Maria Sanyu'), ('Aisha Nakanwagi', 'Aisha Nakanwagi'), ('Jackline Nagasha', 'Jackline Nagasha'), ('Appolo Mbowa Kibirango', 'Appolo Mbowa Kibirango')], max_length=72, null=True),
        ),
    ]
