# Generated by Django 4.0.4 on 2024-04-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_alter_jotfeedback_ces_easy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotfeedback',
            name='csobranch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotfeedback',
            name='csoname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotfeedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotfeedback',
            name='tstamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotfeedback',
            name='yourphone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
