# Generated by Django 4.0.4 on 2024-04-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0004_alter_jotfeedback_csobranch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotfeedback',
            name='tstamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
