# Generated by Django 4.0.4 on 2023-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_role_id', models.IntegerField()),
                ('nssf_no', models.CharField(max_length=255)),
                ('employer_name', models.CharField(max_length=255)),
                ('registry_dt', models.DateField(blank=True, null=True)),
                ('party_role_type_descr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employers',
            },
        ),
        migrations.CreateModel(
            name='Forclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('cancelled', 'Cancelled'), ('first_reviewed', 'First_reviewed'), ('resubmited', 'Resubmited'), ('assigned', 'Assigned'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('approved', 'Approved')], default='initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.CharField(max_length=130)),
                ('nssf_no', models.CharField(max_length=130)),
                ('reason', models.CharField(choices=[('nira', 'Employer closed in NIRA'), ('others', 'Others')], max_length=30)),
                ('review_comment', models.TextField(blank=True)),
                ('next_action_user', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Assessors'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_action_forclosures', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(limit_choices_to={'groups__name': 'Supervisors'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_forclosures', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forclosures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForclosureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comment', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflowapp.forclosure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forclosure_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.CharField(max_length=130)),
                ('nssf_no', models.CharField(max_length=130)),
                ('activity_done', multiselectfield.db.fields.MultiSelectField(choices=[('member_reg', 'Member registration'), ('roadshow', 'Roadshow'), ('audit', 'Compliance Audit'), ('inspection', 'Inspection'), ('senstisation', 'Senstisation'), ('support', 'Support'), ('recovery', 'Collections recovery'), ('emp_reg', 'Employer registration'), ('mapping', 'Mapping'), ('suspe', 'Suspence clearence'), ('closure', 'Employer closure')], max_length=96)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflowapp.engagement')),
                ('forclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflowapp.forclosure')),
            ],
        ),
    ]
