# Generated by Django 5.1 on 2024-12-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_role_id', models.IntegerField()),
                ('nssf_no', models.CharField(max_length=255)),
                ('employer_name', models.CharField(max_length=255)),
                ('registry_dt', models.DateField(blank=True, null=True)),
                ('party_role_type_descr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employers',
            },
        ),
    ]
