# Generated by Django 4.0.4 on 2023-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='reference_date',
        ),
        migrations.AddField(
            model_name='engagement',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
