# Generated by Django 4.0.4 on 2023-07-15 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0002_remove_engagement_reference_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagement',
            name='state',
            field=django_fsm.FSMField(choices=[('recorded', 'Recorded'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='recorded', max_length=50),
        ),
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflowapp.engagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
