# Generated by Django 4.0.4 on 2023-07-19 16:03

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0004_alter_engagement_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='state',
            field=django_fsm.FSMField(choices=[('recorded', 'Recorded'), ('forwarded', 'forwarded'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='recorded', max_length=50),
        ),
    ]
