# Generated by Django 4.0.4 on 2023-07-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0007_remove_engagementlog_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
