# Generated by Django 4.0.4 on 2023-07-22 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0009_alter_engagement_activity_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('recorded', 'Recorded'), ('forwarded', 'forwarded'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='recorded', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject', models.CharField(max_length=130)),
                ('action_date', models.DateTimeField()),
                ('any_other_info', models.CharField(max_length=130)),
                ('remark', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_generalcases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalcases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralcaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflowapp.generalcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalcase_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
