# Generated by Django 4.0.4 on 2023-07-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0010_generalcase_generalcaselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='generalcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflowapp.generalcase'),
        ),
    ]
