# Generated by Django 4.0.4 on 2023-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0011_attachment_generalcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='forclosure',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
