# Generated by Django 4.0.4 on 2023-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0012_forclosure_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclosure',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
