# Generated by Django 4.0.4 on 2024-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0013_alter_forclosure_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='reason_for_non_compliance',
            field=models.CharField(blank=True, choices=[('inconsistent_funding', 'Inconsistent Funding From Government/Donors'), ('covid_19_effects', 'Covid-19 Effects'), ('economic_strain', 'Economic Strain And Cash Flow Challenges'), ('employer_registered', 'Employer Was Registered But Hasn’t Started Operating'), ('unable_to_locate', 'Inability To Locate Employer/Brief Case Company'), ('hard_to_reach', 'Hard To Reach Employer'), ('high_employer_to_rm_ratio', 'High Employer To Rm Ratio'), ('ignorance_of_law', 'Ignorance Of The NSSF Law'), ('informal_closure', 'Informal Employer Closure'), ('informal_employment', 'Informal Employments(Casual Laborers)'), ('lack_of_trust', 'Lack Of Trust In The Brand'), ('non_payment_school_holidays', 'Non-payment During School Holidays'), ('system_issues', 'Painful System Experiences And Breakdown/Internet Connectivity Issues'), ('political_instability', 'Political Instability'), ('political_interference', 'Political Interference And Restricted Access To Employer Premises'), ('stubborn_employer', 'Stubborn And Adamant Employer'), ('unfavorable_registration_requirements', 'Unfavorable Registration Requirements For New Members And Employers')], max_length=50, null=True),
        ),
    ]
