# Generated by Django 4.0.4 on 2024-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0016_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcr_resolved', models.BooleanField(blank=True, null=True)),
                ('nps_rating', models.IntegerField(blank=True, null=True)),
                ('ces_easy', models.BooleanField(blank=True, null=True)),
                ('overall_satisfaction', models.BooleanField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
