# Generated by Django 4.0.4 on 2024-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0019_feedback4'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback4',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback4',
            name='ces_easy',
            field=models.IntegerField(blank=True, choices=[(1, 'Very hard'), (2, 'Hard'), (3, 'Easy'), (4, 'Very easy')], null=True),
        ),
        migrations.AddField(
            model_name='feedback4',
            name='fcr_resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback4',
            name='overall_satisfaction',
            field=models.IntegerField(blank=True, choices=[(0, 'Not satisfied'), (1, 'Satisfied')], null=True),
        ),
    ]
