# Generated by Django 4.0.4 on 2024-03-05 04:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0021_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Walkin', 'Walkin'), ('Call center', 'Call center'), ('Online', 'Online')], max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('nssf_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fcr_resolved', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True)),
                ('ces_easy', models.IntegerField(blank=True, choices=[(1, 'Very hard'), (2, 'Hard'), (3, 'Easy'), (4, 'Very easy')], null=True)),
                ('overall_satisfaction', models.IntegerField(blank=True, choices=[(0, 'Not satisfied'), (1, 'Satisfied')], null=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_by', models.ForeignKey(limit_choices_to={'groups__name': 'Supervisors'}, on_delete=django.db.models.deletion.CASCADE, related_name='Outbound_served_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
