# Generated by Django 4.0.4 on 2024-03-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0022_outbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='channel',
            field=models.CharField(choices=[('Walkin', 'Walkin'), ('Call center', 'Call center'), ('Online', 'Online'), ('NPS', 'NPS'), ('Look & Feel', 'Look & Feel'), ('First contact resolution', 'First contact resolution')], max_length=100),
        ),
    ]
