# Generated by Django 4.0.4 on 2024-03-05 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0023_alter_outbound_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='nps',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
