# Generated by Django 4.0.4 on 2024-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0024_alter_outbound_nps'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='back_office_reasons',
            field=models.CharField(blank=True, choices=[('Easy finding and recognizing', 'Easy finding and recognizing'), ('Difficult finding and recognizing', 'Difficult finding and recognizing'), ('Quick/Fast escalation process', 'Quick/Fast escalation process'), ('Slow/poor escalation process', 'Slow/poor escalation process'), ('Up to date contributions', 'Up to date contributions'), ('Missing contributions', 'Missing contributions'), ('Fast Benefits process', 'Fast Benefits process'), ('Slow/delayed benefits process', 'Slow/delayed benefits process'), ('Process simplicity', 'Process simplicity'), ('Process difficulty', 'Process difficulty'), ('System is fast and stable', 'System is fast and stable'), ('System is slow and unstable', 'System is slow and unstable'), ('Acceptable waiting time', 'Acceptable waiting time'), ('Long waiting time', 'Long waiting time'), ('Limited product offering', 'Limited product offering'), ('Limited language offering', 'Limited language offering'), ('Wrong interest calculation', 'Wrong interest calculation'), ('Good/high interest', 'Good/high interest'), ('Poor/low interest', 'Poor/low interest'), ('Positive organizational reputation', 'Positive organizational reputation'), ('Negative organizational reputation', 'Negative organizational reputation'), ('Delayed system updates', 'Delayed system updates'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='branch',
            field=models.CharField(blank=True, choices=[('Acacia', 'Acacia'), ('Arua', 'Arua'), ('Bakuli', 'Bakuli'), ('Bugolobi', 'Bugolobi'), ('Customer Service Center', 'Customer Service Center'), ('Entebbe', 'Entebbe'), ('Fort Portal', 'Fort Portal'), ('Gulu', 'Gulu'), ('Hoima', 'Hoima'), ('Ishaka', 'Ishaka'), ('Jinja', 'Jinja'), ('Kabale', 'Kabale'), ('Kampala City', 'Kampala City'), ('Lira', 'Lira'), ('Masaka', 'Masaka'), ('Masindi', 'Masindi'), ('Mbale', 'Mbale'), ('Mbarara', 'Mbarara'), ('Moroto', 'Moroto'), ('Mukono', 'Mukono'), ('Soroti', 'Soroti'), ('Tororo', 'Tororo')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='front_office_reasons',
            field=models.CharField(blank=True, choices=[('Good/positive CSO attitude', 'Good/positive CSO attitude'), ('Poor/negative attitude', 'Poor/negative attitude'), ('Good/clear CSO explanation', 'Good/clear CSO explanation'), ('Poor/unclear CSO explanation', 'Poor/unclear CSO explanation'), ('Fast/Quick CSO handling time', 'Fast/Quick CSO handling time'), ('Slow/delayed CSO handling time', 'Slow/delayed CSO handling time'), ('CSO knowledgeable', 'CSO knowledgeable'), ('CSO not knowledgeable', 'CSO not knowledgeable'), ('Good CSO listening skills', 'Good CSO listening skills'), ('Poor CSO listening skill', 'Poor CSO listening skill'), ('Full CSO attention', 'Full CSO attention'), ('Divided CSO attention', 'Divided CSO attention'), ('Quick/Good CSO resolution', 'Quick/Good CSO resolution'), ('Good CSO skill', 'Good CSO skill'), ('Poor CSO skill', 'Poor CSO skill'), ('Nothing extra ordinary', 'Nothing extra ordinary'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='reason_for_visit',
            field=models.CharField(blank=True, choices=[('Balance request', 'Balance request'), ('Benefits follow up', 'Benefits follow up'), ('Benefits verification', 'Benefits verification'), ('Call Center login/logout', 'Call Center login/logout'), ('Claim inquiry', 'Claim inquiry'), ('Claim received', 'Claim received'), ('Clearance certificate', 'Clearance certificate'), ('Clearance of sheet B', 'Clearance of sheet B'), ('Compliance Audit', 'Compliance Audit'), ('Conduct roadshows', 'Conduct roadshows'), ('Contact update', 'Contact update'), ('Contributions receipting', 'Contributions receipting'), ('Corporate social responsibility', 'Corporate social responsibility'), ('COVID Invalidity benefits', 'COVID Invalidity benefits'), ('COVID Survivor’s benefits', 'COVID Survivor’s benefits'), ('Customer engagement message', 'Customer engagement message'), ('Discussion of draft audit report', 'Discussion of draft audit report'), ('Docked Pas claims', 'Docked Pas claims'), ('Duplicate cards', 'Duplicate cards'), ('Employee engagement collection', 'Employee engagement collection'), ('Employee registration', 'Employee registration'), ('Employer registration', 'Employer registration'), ('Financial literacy', 'Financial literacy'), ('General inquiry', 'General inquiry'), ('Inspection of employers', 'Inspection of employers'), ('Issuing clearance certificate', 'Issuing clearance certificate'), ('KYC Updates', 'KYC Updates'), ('Member details update', 'Member details update'), ('Midterm access inquiry', 'Midterm access inquiry'), ('Midterm claim follow up', 'Midterm claim follow up'), ('Midterm claim received', 'Midterm claim received'), ('No show customer', 'No show customer'), ('NSSF number retrieval', 'NSSF number retrieval'), ('NSSF Smart card', 'NSSF Smart card'), ('Office location', 'Office location'), ('Office opening hours', 'Office opening hours'), ('Outbound escalation', 'Outbound escalation'), ('Real estate inquiry', 'Real estate inquiry'), ('Self assessment test (SAT)', 'Self assessment test (SAT)'), ('Sensitization', 'Sensitization'), ('SmartLife', 'SmartLife'), ('Spam mail.', 'Spam mail.'), ('Statement request', 'Statement request'), ('Statement enquiries', 'Statement enquiries'), ('Statement update', 'Statement update'), ('Unsuccessful calls', 'Unsuccessful calls'), ('Voluntary company registration', 'Voluntary company registration'), ('Voluntary inquiry', 'Voluntary inquiry'), ('Voluntary member registration', 'Voluntary member registration'), ('Whistleblower', 'Whistleblower')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='verbatim_rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
