# Generated by Django 4.0.4 on 2024-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0025_outbound_back_office_reasons_outbound_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='call_closure',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='emotional_connection',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25')], null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='greeting_and_enthusiasm',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='hold_procedure',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='resolution_and_professionalism',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35')], null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='zero_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='channel',
            field=models.CharField(choices=[('Walkin', 'Walkin'), ('Call center', 'Call Quality'), ('Online', 'Online'), ('NPS', 'NPS'), ('Look & Feel', 'Look & Feel'), ('First contact resolution', 'First contact resolution')], max_length=100),
        ),
    ]
