# Generated by Django 4.0.4 on 2024-03-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0027_alter_outbound_call_closure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapped_employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssf_no', models.CharField(max_length=20)),
                ('employer_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
