# Generated by Django 4.0.4 on 2024-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0029_alter_mapped_employers_employer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps_rating', models.IntegerField()),
                ('fcr_resolved', models.BooleanField(blank=True, null=True)),
                ('ces_easy', models.IntegerField(blank=True, choices=[(1, 'Very hard'), (2, 'Hard'), (3, 'Easy'), (4, 'Very easy')], null=True)),
                ('overall_satisfaction', models.IntegerField(blank=True, choices=[(0, 'Not satisfied'), (1, 'Satisfied')], null=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('first_name', models.CharField(max_length=255)),
                ('yourphone', models.CharField(max_length=255)),
                ('csobranch', models.CharField(max_length=255)),
                ('csoname', models.CharField(max_length=255)),
                ('tstamp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
