# Generated by Django 4.0.4 on 2024-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0030_jotfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotfeedback',
            name='fcr_resolved',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
    ]
