# Generated by Django 4.0.4 on 2024-06-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0033_alter_jotfeedback_ces_easy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='main_activity',
            field=models.CharField(blank=True, choices=[('account4noncompliance', 'Account for non-compliance'), ('member_reg', 'Member registration'), ('legal', 'Record legal case')], max_length=100, null=True),
        ),
    ]
