# Generated by Django 4.0.4 on 2024-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0034_engagement_main_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_identificat_val', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('init_member_suspense_contr', models.FloatField(blank=True, null=True)),
                ('ident_member_suspense_contr', models.FloatField(blank=True, null=True)),
                ('cur_member_suspense_contr', models.FloatField(blank=True, null=True)),
                ('init_interest_suspense_amount', models.FloatField(blank=True, null=True)),
                ('cur_interest_suspense_amount', models.FloatField(blank=True, null=True)),
                ('ident_interest_suspense', models.FloatField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_identificat_val', models.CharField(blank=True, max_length=255, null=True)),
                ('trn', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('statutory_ins_detail_id', models.FloatField(blank=True, null=True)),
                ('employerno', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
