# Generated by Django 5.1.4 on 2025-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URA_tins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('taxpayer_id', models.CharField(max_length=20, unique=True)),
                ('business_start_date', models.DateField(blank=True, null=True)),
                ('registration_status', models.CharField(blank=True, choices=[('REGD', 'Registered'), ('CNCL', 'Cancelled')], max_length=50, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('current_sector_main_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('taxpayer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_person_landline', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('business_certificate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_of_incorporation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_district', models.CharField(blank=True, max_length=100, null=True)),
                ('business_building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_country', models.CharField(blank=True, max_length=100, null=True)),
                ('business_plot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('business_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('business_sub_country', models.CharField(blank=True, max_length=100, null=True)),
                ('business_trade_center', models.CharField(blank=True, max_length=100, null=True)),
                ('business_village', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
