# Generated by Django 5.1.4 on 2025-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0002_ura_tins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ura_tins',
            name='business_building_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_certificate_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_plot_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_start_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_sub_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_trade_center',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='business_village',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='certificate_of_incorporation_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='contact_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='contact_person_designation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='contact_person_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='contact_person_landline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='contact_person_mobile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='current_sector_main_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='landline_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='mobile_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='registration_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='taxpayer_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='taxpayer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='taxpayer_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura_tins',
            name='trading_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
