# Generated by Django 5.1.4 on 2025-01-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0003_alter_ura_tins_business_building_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerno', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_suspense_contr', models.FloatField(blank=True, null=True)),
                ('records_count', models.IntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('scope_months', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='suspense',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
