# Generated by Django 5.1.4 on 2025-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0004_suspensesummary_suspense_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerno', models.CharField(max_length=50, unique=True, verbose_name='Employer Number')),
                ('employer_name', models.CharField(max_length=255, verbose_name='Employer Name')),
                ('tin', models.CharField(max_length=20, verbose_name='TIN')),
                ('name_from_ura', models.CharField(max_length=255, verbose_name='Name from URA')),
                ('matching_percentage', models.IntegerField(verbose_name='Matching Percentage')),
                ('source_of_tin', models.CharField(max_length=50, verbose_name='Source of TIN')),
            ],
            options={
                'verbose_name': 'Fund TIN',
                'verbose_name_plural': 'Fund TINs',
                'ordering': ['employerno'],
            },
        ),
    ]
