# Generated by Django 5.1.4 on 2025-02-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0005_fundtins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspensesummary',
            options={'verbose_name': 'Suspense Summary', 'verbose_name_plural': 'Suspense Summaries'},
        ),
        migrations.AddField(
            model_name='suspensesummary',
            name='tin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspense_summaries', to='suspenseapp.fundtins'),
        ),
    ]
