# Generated by Django 5.1.4 on 2025-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0006_alter_suspensesummary_options_suspensesummary_tin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MEMBER_NUMBER', models.CharField(max_length=50, verbose_name='Member Number')),
                ('MEMBER_NAME', models.CharField(max_length=255, verbose_name='Member Name')),
                ('EMPLOYER_NAME', models.CharField(max_length=255, verbose_name='Employer Name')),
                ('START_YEAR', models.IntegerField(blank=True, null=True, verbose_name='Start Year')),
                ('END_YEAR', models.IntegerField(blank=True, null=True, verbose_name='End Year')),
                ('CATEGORY', models.CharField(max_length=10, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment Histories',
            },
        ),
    ]
