# Generated by Django 5.1.4 on 2025-02-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0007_employmenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='CATEGORY',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='EMPLOYER_NAME',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='END_YEAR',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='MEMBER_NAME',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='MEMBER_NUMBER',
            new_name='member_number',
        ),
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='START_YEAR',
            new_name='start_year',
        ),
    ]
