# Generated by Django 5.1.4 on 2025-02-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0009_alter_employmenthistory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='member_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Member Number'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Start Year'),
        ),
    ]
