# Generated by Django 5.1.4 on 2025-03-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0011_alter_employmenthistory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspenseLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssf_name', models.CharField(max_length=255)),
                ('ura_name', models.CharField(max_length=255)),
                ('percentage_match', models.IntegerField()),
                ('suspense', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('contact', models.TextField()),
                ('nssf_period', models.CharField(max_length=7)),
                ('ura_period', models.CharField(max_length=7)),
                ('employer_name', models.CharField(max_length=255)),
                ('employerno', models.CharField(max_length=50)),
                ('employee_tin', models.CharField(max_length=50)),
                ('basic_salary', models.BigIntegerField()),
                ('gross_total_income', models.BigIntegerField()),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('member_nssfno', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
