# Generated by Django 5.1.4 on 2025-03-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0012_suspenseleads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspenseleads',
            old_name='member_nssfno',
            new_name='nssfno_by_email',
        ),
        migrations.AddField(
            model_name='suspenseleads',
            name='nssfno_by_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
