# Generated by Django 5.1.4 on 2025-03-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0013_rename_member_nssfno_suspenseleads_nssfno_by_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspenseleads',
            old_name='employer_name',
            new_name='member_name',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='employee_tin',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='employerno',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='gross_total_income',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='nssf_name',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='nssf_period',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='nssfno_by_email',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='nssfno_by_phone',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='percentage_match',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='suspense',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='ura_name',
        ),
        migrations.RemoveField(
            model_name='suspenseleads',
            name='ura_period',
        ),
    ]
