# Generated by Django 5.1.4 on 2025-03-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0014_rename_employer_name_suspenseleads_member_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspenseleads',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
