# Generated by Django 5.1.4 on 2025-03-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0015_alter_suspenseleads_member_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuspenseLeads',
        ),
    ]
