# Generated by Django 5.1.4 on 2025-03-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0016_delete_suspenseleads'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspenseLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(max_length=255)),
                ('init_member_suspense_contr', models.FloatField()),
                ('employer_name', models.CharField(max_length=255)),
                ('employerno', models.CharField(max_length=255)),
                ('member_month_year_s', models.CharField(max_length=255)),
                ('EmployeeName', models.CharField(max_length=255)),
                ('EmployeeTIN', models.BigIntegerField()),
                ('EmployeeToDt', models.CharField(max_length=255)),
                ('BasicSalary', models.FloatField()),
                ('GrossTotIncome', models.FloatField()),
                ('member_month_year', models.CharField(max_length=255)),
                ('ura_based_nssf', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
                ('percentage_match', models.FloatField()),
                ('num_best_matches', models.IntegerField()),
                ('mobile', models.CharField(max_length=255)),
                ('nssfno_by_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('nssfno_by_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
