# Generated by Django 5.1.4 on 2025-03-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0017_suspenseleads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuspenseLeads',
        ),
    ]
