# Generated by Django 5.1.4 on 2025-03-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspenseapp', '0019_suspenseleads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuspenseLeads',
        ),
    ]
